language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install numpy
  - python setup.py build_ext --inplace
# command to run tests
script: nosetests --with-doctest
