package:
  name: pyquante2_pure
  version: "2.0"

source:
  git_url: https://github.com/rpmuller/pyquante2.git
  git_rev: pure

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

build:
  noarch_python: True

test:
  import:
    - pyquante2

about:
  home: http://github.com/rpmuller/pyquante2
  license: BSD
  summary: "Python quantum chemistry reloaded"
