package:
  name: pyquante2
  version: "2.0"

source:
  git_url: http://github.com/rpmuller/pyquante2.git

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy

test:
  requires:
    - nose
  

about:
  home: http://github.com/rpmuller/pyquante2
  license: BSD
  summary: "Python quantum chemistry reloaded"
